//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyNamespace
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Program
	{
		public static Document Document
		{
			get;
			set;
		}

		public static void Main()
		{
            Document = new Document();
            Document.Display();
        }

	}
}

